# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _tnode
else:
    import _tnode

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _tnode.delete_SwigPyIterator

    def value(self):
        return _tnode.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _tnode.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _tnode.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _tnode.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _tnode.SwigPyIterator_equal(self, x)

    def copy(self):
        return _tnode.SwigPyIterator_copy(self)

    def next(self):
        return _tnode.SwigPyIterator_next(self)

    def __next__(self):
        return _tnode.SwigPyIterator___next__(self)

    def previous(self):
        return _tnode.SwigPyIterator_previous(self)

    def advance(self, n):
        return _tnode.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _tnode.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _tnode.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _tnode.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _tnode.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _tnode.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _tnode.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _tnode:
_tnode.SwigPyIterator_swigregister(SwigPyIterator)

class TNode(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _tnode.TNode_swiginit(self, _tnode.new_TNode(*args))
    uri = property(_tnode.TNode_uri_get, _tnode.TNode_uri_set)
    ic = property(_tnode.TNode_ic_get, _tnode.TNode_ic_set)
    lc = property(_tnode.TNode_lc_get, _tnode.TNode_lc_set)
    fc = property(_tnode.TNode_fc_get, _tnode.TNode_fc_set)
    tc = property(_tnode.TNode_tc_get, _tnode.TNode_tc_set)
    _is = property(_tnode.TNode__is_get, _tnode.TNode__is_set)
    ls = property(_tnode.TNode_ls_get, _tnode.TNode_ls_set)
    fs = property(_tnode.TNode_fs_get, _tnode.TNode_fs_set)
    f = property(_tnode.TNode_f_get, _tnode.TNode_f_set)
    parents = property(_tnode.TNode_parents_get, _tnode.TNode_parents_set)
    children = property(_tnode.TNode_children_get, _tnode.TNode_children_set)
    __swig_destroy__ = _tnode.delete_TNode

# Register TNode in _tnode:
_tnode.TNode_swigregister(TNode)



